# Generated by Django 5.0.7 on 2024-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
