# Generated by Django 5.0.7 on 2024-08-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordermodel_customerpaymentdetails_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='customerpaymentdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customerpaymentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='CustomerPaymentDetails',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
