# Generated by Django 5.0.7 on 2024-07-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_productmodel_img_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='quantity',
        ),
    ]
