# Generated by Django 5.0.7 on 2024-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_orderitemmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
