# Generated by Django 5.0.7 on 2024-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_customerpaymentdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
