# Generated by Django 5.0.7 on 2024-08-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_customerpaymentdetails_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpaymentdetails',
            name='currency_code',
        ),
    ]
