# Generated by Django 5.0.7 on 2024-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_customerpaymentdetails_currency_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
