# Generated by Django 5.0.7 on 2026-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_delete_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
