# Generated by Django 5.0.7 on 2026-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_customerpaymentdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpaymentdetails',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
