# Generated by Django 5.0.7 on 2026-04-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_customerpaymentdetails_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentdetails',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay')], default='razorpay', max_length=20),
        ),
    ]
